version: "3"

services:
  web:
    build: .
    container_name: opea
    restart: always
    volumes:
      - ./:/opea
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        pnpm dev

  book:
    build: .
    container_name: opea-book
    restart: always
    volumes:
      - ./:/opea
    ports:
      - 6006:6006
    command:
      - /bin/sh
      - -c
      - |
        pnpm storybook
